packages:
  - 'apps/*'
  - 'apps/frontend'
  - 'apps/cron-jobs'
  - 'packages/*'
  - 'packages/valkey-client'
  - 'packages/drizzle-client'
  - 'packages/game-logic'
allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  svelte-preprocess: true
