packages:
  - 'apps/*'
  - 'apps/frontend'
  - 'apps/cron-jobs'
  - 'packages/*'
  - 'packages/valkey-client'
  - 'packages/drizzle-client'
  - 'packages/game-logic'
allowBuilds:
  '@prisma/client': true
  '@tailwindcss/oxide': true
  better-sqlite3: true
  esbuild: true
  svelte-preprocess: true
minimumReleaseAgeExclude:
  - '@lucide/svelte@1.43.0'
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
